### ISSUE TITLE
RFC:  Should this be a Public Repository?

### ISSUE THREAD

**Issue by ajstadlin** [GridProtectionAlliance/DeveloperExercises#1]
Request for Comments:

Although these exercises are currently working for me personally as an entry level GPA developer; are these exercises compatible with the Grid Protection Alliance guidelines and GPA senior developers' practices?

//aj

**Comment by ajstadlin** [comment]
I made the DeveloperExercises project Public to use one of the exercises as a test case for an openPDC issue.

Let me know if this repository should be reverted back to Private status.

//aj

**Comment by ritchiecarroll** [comment]
Sure AJ - please keep the repository public - I'll take a look at these as soon as I can. In the meantime I am sure these will be helpful to anyone trying to learn...
